version: '3.7'
services:
  jenkins:
    image: registry.cn-hangzhou.aliyuncs.com/jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_UC_DOWNLOAD=https://mirrors.tuna.tsinghua.edu.cn/jenkins
      - JENKINS_OPTS="-Dhudson.model.UpdateCenter.updateCenterUrl=http://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/update-center.json"
    volumes:
      - $PWD/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
